// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CrossTextController from "./cross_text_controller"
application.register("cross-text", CrossTextController)

import FilterTasksController from "./filter_tasks_controller"
application.register("filter-tasks", FilterTasksController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MarkController from "./mark_controller"
application.register("mark", MarkController)
