
meta_product_name: "50:50"
meta_title: "50:50 - Share the mental load"
meta_description: "Share tasks with your partner and help make teamwork easier!"
meta_image: "apple-icon.png" # should exist in `app/assets/images/`
